# Generated by Django 2.0.5 on 2019-03-12 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0002_auto_20190312_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertweet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
