# Generated by Django 2.0.5 on 2019-03-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0003_auto_20190312_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertweet',
            name='title',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertweet',
            name='content',
            field=models.TextField(),
        ),
    ]
