# Generated by Django 3.0.2 on 2020-05-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0006_hostel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='p_id',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
