# Generated by Django 3.0.2 on 2020-05-10 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0008_auto_20200510_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='Total',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='Total',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='Total',
        ),
    ]
