# Generated by Django 3.0.2 on 2020-05-11 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0009_auto_20200510_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='dept_ratings',
        ),
    ]
