# Generated by Django 3.0.2 on 2020-05-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0010_remove_department_dept_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
