# Generated by Django 2.0.5 on 2020-05-11 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tweet', '0011_auto_20200511_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='Hostel_Name',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
