# Generated by Django 2.0.5 on 2019-03-02 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=30)),
                ('year_of_study', models.CharField(max_length=1)),
                ('college_name', models.CharField(max_length=40)),
                ('college_location', models.CharField(max_length=20)),
                ('mobilenumber', models.CharField(max_length=10)),
                ('email_verified', models.BooleanField(default=False)),
                ('event1', models.BooleanField(default=False)),
                ('event2', models.BooleanField(default=False)),
                ('event3', models.BooleanField(default=False)),
                ('event4', models.BooleanField(default=False)),
                ('event5', models.BooleanField(default=False)),
                ('event6', models.BooleanField(default=False)),
                ('event7', models.BooleanField(default=False)),
                ('event8', models.BooleanField(default=False)),
                ('event9', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
